apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: collectl
  namespace: openshift4-debug
  labels:
    app: openshift4-debug
spec:
  output:
    to:
      kind: ImageStreamTag
      name: collectl:latest
  source:
    dockerfile: |
      FROM registry.access.redhat.com/ubi7/ubi:7.8
      RUN yum install https://archives.fedoraproject.org/pub/archive/epel/7/x86_64/Packages/e/epel-release-7-14.noarch.rpm -y && \
          yum install collectl-4.3.0-5.el7 pciutils hostname sysvinit-tools -y && \
          yum clean all
      COPY ./entrypoint.sh /root/
      RUN chmod 741 /root/entrypoint.sh
      CMD ["/root/entrypoint.sh"]
    type: Dockerfile
    configMaps:
    - configMap:
        name: collectl-entrypoint
      destinationDir: entrypoint
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - type: ConfigChange
